services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        MONGO_URI: ${MONGO_URI}
    networks:
      - app-network
    volumes:
      - ./data:/app/data

  db:
    image: mongo:5.0
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - mongo-data:/data/db # Persistent volume for MongoDB data
    networks:
      - app-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run ats
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data: # Named volume for persistent storage

networks:
  app-network:
    driver: bridge
