name: Code Coverage

on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create env file
        run: |
          echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}" > .env

      - name: Test with pytest
        run: pytest --tb=line

      - name: Generate coverage
        run: pytest --tb=line --cov-config=.coveragerc --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
