name: Tests

on: [push]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Replace '3.x' with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create env file
        run: |
          echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      - name: Test with pytest
        run: pytest --tb=line
