name: Unittest

on:
  push:
    branches: [main, workflows]
  schedule:
    - cron: '00 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create env file
        run: |
            echo "CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}" > .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      - name: Run Unit Tests
        run: |
          run: pytest --tb=line